### ISSUE TITLE
Add report file to attachments

### ISSUE THREAD

**Issue by LMT337** [mgi-qc/exome_report#12]
I don't think we need the confluence link in the final report? @awollam? 

Attachments should include report file as well:

Attachments:
2858386.cwl.results.061419.tsv

Attachments:
2858386.cwl.report.061419.txt
2858386.cwl.results.061419.tsv

**Comment by awollam** [comment]
Confluence link is there so we can easily go to the page as well as for anyone who wants to look up information concerning sequencing such as library info etc.

**Comment by awollam** [comment]
Please do not remove the link in the report.

**Comment by LMT337** [comment]
@awollam , sounds good, keep the link, update 'Attachments:' to include report file for this issue.

**Comment by LMT337** [comment]
Confluence link not removed, template file needed variable added.
