### ISSUE TITLE
Return error if no metrics found to check

### ISSUE THREAD

**Issue by LMT337** [mgi-qc/exome_report#14]
Traceback (most recent call last):
  File "/gscuser/awollam/aw/exome_report.py", line 166, in <module>
    if float(line['PCT_TARGET_BASES_20X']) < 0.70:
TypeError: float() argument must be a string or a number, not 'NoneType'

Error due to not finding metric in file, value is None, error comes when trying to check pass fail with NoneType value.

**Comment by antonaccitj** [comment]
Fixed in branch 20Xfix
