### ISSUE TITLE
Fix Syntax error

### ISSUE THREAD

**Issue by LMT337** [mgi-qc/exome_report#20]
Error: 

Running exome_report on cwl exome metrics files.
----------
/storage1/fs1/gtac-mgi/Active/Bioinformatics_analysis/mds_contract_gms_compute1/mds_analysis/bin/qc/cwl_exome_report/exome_report.py:112: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if ad_met_in is 'y':
/storage1/fs1/gtac-mgi/Active/Bioinformatics_analysis/mds_contract_gms_compute1/mds_analysis/bin/qc/cwl_exome_report/exome_report.py:132: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif ad_met_in is 'n':
/storage1/fs1/gtac-mgi/Active/Bioinformatics_analysis/mds_contract_gms_compute1/mds_analysis/bin/qc/cwl_exome_report/exome_report.py:225: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if seq_in is 'y':
/storage1/fs1/gtac-mgi/Active/Bioinformatics_analysis/mds_contract_gms_compute1/mds_analysis/bin/qc/cwl_exome_report/exome_report.py:236: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif seq_in is 'n':

Confluence link:
https://confluence.ris.wustl.edu/pages/viewpage.action?spaceKey=AD&title=WorkOrder+2868179 
Would you like to require additional metrics for 2868179? y/n: 

Investigate this error, add details to this ticket on cause.  Fix the bug.

**Comment by billtell** [comment]
This issue will resolve by https://github.com/mgi-qc/exome_report/issues/22 and issue23
