### ISSUE TITLE
Update DT path generation for output files

### ISSUE THREAD

**Issue by LMT337** [mgi-qc/exome_report#21]
Find DT transfer requirements for file staging required by the genome command.   Update dir creation/output for exome_report script.

**Comment by LMT337** [comment]
In addition, automate the running of this command, requirements: 
DT dir MUST NOT exist
Create new DT dir 
Run this command (example):
genome model cwl-pipeline prep-for-transfer --md5sum --directory=<DT DIRECTORY> --builds <comma separated list of build_ids>
*Script is already making the comma separated list to output the formatted command to the Data_transfer_help file and trying to add the DT dir.  WIll just need to fix the <DT DIRECTORY> issue first, then run this command if conditions to run are successful. 
 
If DT dir exists notify user via terminal print statement.

**Comment by LMT337** [comment]
From Andrew: 

I don’t think that it matters so long as it’s a child of:
/storage1/fs1/gtac-mgi/Active/

I believe that there are some things (maybe even past MDS DTS) here:
/storage1/fs1/gtac-mgi/Active/Bioinformatics_ops/

Possibly make mds_transfer directory under Active dir. 

dir format name is:
<woid>_date
2866757_05112

Logic for this should already be in exome_report

**Comment by LMT337** [comment]
DT PATH: 
/storage1/fs1/gtac-mgi/Active/Bioinformatics_analysis/mds_contract_gms_compute1/mds_dt

**Comment by billtell** [comment]
this commit was completed on master branch.
