### ISSUE TITLE
Hardcode additional metric MEAN_TARGET_COVERAGE to 600

### ISSUE THREAD

**Issue by LMT337** [mgi-qc/exome_report#22]
Would you like to require additional metrics for 2868179? y/n: y

Please enter a MEAN_TARGET_COVERAGE value for 2868179, or enter 0 to skip metric:  

Should not ask for this, should be a default requirment set to a value of 600.

**Comment by billtell** [comment]
metrics_tracked = ['PASS_SAMPLES', 'ALN_FAIL', 'MEAN_TAR_COV_PASS', 'MEAN_TAR_COV_FAIL']

mt_value = 600

add_met = 'MEAN_TARGET_COVERAGE (minimum requirement) : {}'.format(mt_value)
